README.md
lib/index.js
lib/index.test.js
yarn.lock

feat(render): language support with `hl`

---

example/src/config/index.js
lib/index.test.js
package.json
yarn.lock

chore: run prettier on precommit

---

README.md
lib/index.js
lib/index.test.js

fix: no default classname

---

lib/index.js
lib/index.test.js

fix: do not inject script when one already present

---

README.md
lib/index.js
lib/index.test.js
lib/types/index.js
lib/utils/index.js

clear on unmount, change deprecated methods, refactor

---

README.md
lib/webpack.config.js

build: ssr ready

---

example/package.json
example/src/components/input.js
yarn.lock

fix: using formik field outside of formik form crashes the app

---

README.md

docs: improvements

---

lib/index.js
lib/index.test.js
lib/utils/isAnyScriptPresent.js
lib/utils/isAnyScriptPresent.test.js

fix: script detection

---

lib/index.js
lib/index.test.js

fix(theme): support invisible dark mode

---

lib/index.d.ts
lib/package.json

I've created TS definition file for this package in my project so I may as well share it.

Add TypeScript definition file

---

lib/README.md
lib/index.d.ts
lib/index.js
lib/index.test.js

feat: add render prop

---

.eslintignore
lib/index.d.ts
lib/index.js
lib/index.test.js
lib/types/index.js
package.json

Feature: expose getResponse

---

lib/README.md

docs: add info about getResponse

---

example/src/modules/example.js

fixes #185 
**Changes:**
- ~~add `getResponse` instance method to readme~~ already done
- adds `getResponse` example which just `alert`s it

docs: added getResponse instance method

---

lib/index.d.ts

fixes https://github.com/sarneeh/reaptcha/pull/183#issuecomment-569437854

fix: add getResponse method type

---

lib/index.js

fix: update component on className change

---

.changeset/metal-turtles-sniff.md
lib/index.test.tsx
lib/index.tsx

Fix uncaught (in promise) timeout error

---

.changeset/slow-dots-love.md
.changeset/tall-boats-rule.md
example/src/modules/example.tsx
lib/index.test.tsx
lib/index.tsx

refactor callbacks to be able to access local state in functional components

---

.changeset/real-sloths-grab.md
.prettierrc
lib/index.tsx
lib/package.json

fix: support react@^18
